test_work/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.views import defaults as default_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include("users.urls", namespace="users")),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^change/(?P<username>[\w.@+-]+)/$',
        view=views.UserChangeView.as_view(),
        name='change'
    ),

    # URL pattern for the UserDeleteView
    url(
        regex=r'^delete/(?P<username>[\w.@+-]+)/$',
        view=views.UserDeleteView.as_view(),
        name='delete'
    ),

    # URL pattern for the UserCreateView
    url(
        regex=r'^~create/$',
        view=views.UserCreateView.as_view(),
        name='create'
    ),

    # URL pattern for the CreateReportView
    url(
        regex=r'^~create_report/$',
        view=views.CreateReportView.as_view(),
        name='report'
    ),
]

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.utils.functional import cached_property

from .utils import get_random_value

import datetime


@python_2_unicode_compatible
class User(AbstractUser):

    birthday_date = models.DateField(_("User birthday date"), null=True)
    random_int = models.PositiveSmallIntegerField(_("Random integer"), default=get_random_value)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in self._meta.fields]

    @cached_property
    def age(self):
        if self.birthday_date:
            return int((datetime.datetime.now().date()-self.birthday_date).days/365)
        else:
            return None

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import User


class MyUserCreationForm(UserCreationForm):

    error_message = UserCreationForm.error_messages.update({
        'duplicate_username': 'This username has already been taken.'
    })

    class Meta(UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])


class MyUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User

users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, View, ListView, RedirectView, UpdateView
from django.shortcuts import get_object_or_404
from .forms import MyUserCreationForm, MyUserChangeForm
from django.http import HttpResponse

from .models import User
from .templatetags.user_extras import bizz_fuzz, child_protect

import csv


class UserDetailView(DetailView):
    model = User

    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserChangeView(UpdateView):
    form_class = MyUserChangeForm
    slug_field = "username"
    slug_url_kwarg = "username"

    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.POST.get('username')})


class UserListView(ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserDeleteView(RedirectView):

    permanent = True
    url = reverse_lazy('users:list')
    query_string = False

    def get_redirect_url(self, *args, **kwargs):
        user = get_object_or_404(User, username=kwargs['username'])
        user.delete()
        return super(UserDeleteView, self).get_redirect_url(*args, **kwargs)


class UserCreateView(CreateView):
    form_class = MyUserCreationForm
    template_name = 'users/create.html'


class CreateReportView(View):

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="report.csv"'
        writer = csv.writer(response)
        for user in User.objects.all():
            writer.writerow([user.username, user.birthday_date, child_protect(user), user.random_int, bizz_fuzz(user)])
        return response

templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}project_name{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

  </head>

  <body>

    <div class="m-b">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="{% url 'users:list' %}">test_work</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:list' %}">Users list</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:create' %}">Create user</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:report' %}">Create report(csv)</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">

            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">
      <br>

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

      <!-- Tether - a requirement for Bootstrap tooltips -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>
 

templates/users/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create user{% endblock %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <form class="form-horizontal" method="post" action="{% url 'users:create' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                  <br>
                  <div class="controls">
                    <button type="submit" class="btn btn-success">Create</button>
                  </div>
                  <br>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <h2>{{ object.username }}</h2>
        </div>
    </div>


    <div class="row">
        {% for name, value in object.get_fields %}
            <div class="col-sm-12 ">
                {% if value %}
                    {{ name }} => {{ value }}
                {% endif %}
            </div>
        {% endfor %}
    </div>

    <br>

    <div class="row">
        <div class="col-md-12">
            <a type="button" class="btn btn-success" href="{% url 'users:change' object.username %}">Change this user</a>
            <a type="button" class="btn btn-danger" href="{% url 'users:delete' object.username %}">Delete this user</a>
        </div>
    </div>
</div>
{% endblock content %}

templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:change' user.username %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <br>
          <div class="controls">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
          <br>
        </div>
    </form>
{% endblock %}

templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Users{% endblock %}
{% load user_extras %}


{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }} - {{ user|child_protect }} - {{ user|bizz_fuzz }}</h4>
          </a>
        {% endfor %}

    </div>

    <br>
    <a class="btn btn-success" role="button" href="{% url 'users:report' %}">Load report</a>
</div>

{% endblock content %}